INSERT INTO abilities (ability_text_id, ability_name, ability_description)
VALUES
("STENCH", "Stench", "Damaging a target makes it flinch by a small chance"),
("DRIZZLE", "Drizzle", "Summons rain for five turns when switching in"),
("SPEEDBOOST", "Speed Boost", "Raises this Pokémon's Speed stat every turn"),
("BATTLEARMOR", "Battle Armor", "This Pokémon cannot be critically hit"),
("STURDY", "Sturdy", "Cannot be knocked out in one hit if at maximum HP"),
("DAMP", "Damp", "Inhibits self-destruction moves and Aftermath"),
("LIMBER", "Limber", "This Pokémon cannot be paralyzed"),
("SANDVEIL", "Sand Veil", "This Pokémon is harder to hit during a sandstorm"),
("STATIC", "Static", "May paralyze any attacker who makes direct contact"),
("VOLTABSORB", "Volt Absorb", "This Pokémon restores HP if hit by an Electric move"),
("WATERABSORB", "Water Absorb", "This Pokémon restores HP if hit by a Water move"),
("OBLIVIOUS", "Oblivious", "Prevents infatuation, Captivate and Taunt"),
("CLOUDNINE", "Cloud Nine", "This Pokémon negates all weather effects in battle"),
("COMPOUNDEYES", "Compound Eyes", "This Pokémon has notably increased Accuracy"),
("INSOMNIA", "Insomnia", "This Pokémon cannot fall asleep"),
("COLORCHANGE", "Color Change", "Matches the type of any damaging move hitting it"),
("IMMUNITY", "Immunity", "This Pokémon cannot get poisoned"),
("FLASHFIRE", "Flash Fire", "Getting hit by a Fire-type move powers up its own"),
("SHIELDDUST", "Shield Dust", "This Pokémon is immune to additional effects"),
("OWNTEMPO", "Own Tempo", "This Pokémon cannot become confused"),
("SUCTIONCUPS", "Suction Cups", "Cannot be forced to switch out or flee"),
("INTIMIDATE", "Intimidate", "Lowers opponents' Attack stat upon entering battle"),
("SHADOWTAG", "Shadow Tag", "Opponents cannot flee or switch out normally"),
("ROUGHSKIN", "Rough Skin", "Damages any attacker who makes direct contact"),
("WONDERGUARD", "Wonder Guard", "It can only be hit by supereffective moves"),
("LEVITATE", "Levitate", "This Pokémon is immune to Ground-type moves"),
("EFFECTSPORE", "Effect Spore", "Direct contact may cause poison, paralysis or sleep"),
("SYNCHRONIZE", "Synchronize", "Attackers suffer any condition they inflict, too"),
("CLEARBODY", "Clear Body", "Others cannot lower this Pokémon's stats"),
("NATURALCURE", "Natural Cure", "Heals its status condition when switching out"),
("LIGHTNINGROD", "Lightning Rod", "Attracts Electric moves. They raise its Sp. Atk"),
("SERENEGRACE", "Serene Grace", "Has a doubled chance to inflict additional effects"),
("SWIFTSWIM", "Swift Swim", "This Pokémon's Speed stat is doubled during rain"),
("CHLOROPHYLL", "Chlorophyll", "Harsh sunlight doubles this Pokémon's Speed stat"),
("ILLUMINATE", "Illuminate", "Doubles wild encounters when leading the party"),
("TRACE", "Trace", "Copies an opponent's Ability when switched in"),
("HUGEPOWER", "Huge Power", "This Pokémon's Attack stat is doubled in battle"),
("POISONPOINT", "Poison Point", "Attackers making direct contact may be poisoned"),
("INNERFOCUS", "Inner Focus", "This Pokémon will never flinch"),
("MAGMAARMOR", "Magma Armor", "Cannot be frozen. Eggs hatch double as quickly"),
("WATERVEIL", "Water Veil", "This Pokémon cannot be burnt"),
("MAGNETPULL", "Magnet Pull", "Steel-types cannot flee or switch out normally"),
("SOUNDPROOF", "Soundproof", "This Pokémon is immune to sound-based moves"),
("RAINDISH", "Rain Dish", "This Pokémon slowly regains HP during rain"),
("SANDSTREAM", "Sand Stream", "Summons a sandstorm for five turns on switch-in"),
("PRESSURE", "Pressure", "Attacking this Pokémon costs an additional PP"),
("THICKFAT", "Thick Fat", "Only takes halved damage from Ice and Fire moves"),
("EARLYBIRD", "Early Bird", "This Pokémon awakens very quickly from sleep"),
("FLAMEBODY", "Flame Body", "May burn attackers on contact. Eggs hatch fast"),
("RUNAWAY", "Run Away", "This Pokémon can always flee from wild Pokémon"),
("KEENEYE", "Keen Eye", "This Pokémon's Accuracy can't be lowered by others"),
("HYPERCUTTER", "Hyper Cutter", "Others cannot lower this Pokémon's Attack stat"),
("PICKUP", "Pickup", "May find an item in battle or after a victory"),
("TRUANT", "Truant", "This Pokémon can only use a move every second turn"),
("HUSTLE", "Hustle", "Boosts Attack but lowers physical moves' Accuracy"),
("CUTECHARM", "Cute Charm", "May infatuate attackers who make direct contact"),
("PLUS", "Plus", "An ally with Minus or Plus raises its Sp. Atk stat"),
("MINUS", "Minus", "An ally with Plus or Minus raises its Sp. Atk stat"),
("FORECAST", "Forecast", "The weather determines this Pokémon's form"),
("STICKYHOLD", "Sticky Hold", "An item it holds cannot be stolen or knocked off"),
("SHEDSKIN", "Shed Skin", "May heal its own status conditions each turn"),
("GUTS", "Guts", "Status conditions greatly increase its Attack stat"),
("MARVELSCALE", "Marvel Scale", "Status conditions greatly increase its Defense stat"),
("LIQUIDOOZE", "Liquid Ooze", "HP-draining moves damage instead of heal attackers"),
("OVERGROW", "Overgrow", "Boosts Grass-type moves when at a third or less HP"),
("BLAZE", "Blaze", "Boosts Fire-type moves when at a third or less HP"),
("TORRENT", "Torrent", "Boosts Water-type moves when at a third or less HP"),
("SWARM", "Swarm", "Boosts Bug-type moves when at a third or less HP"),
("ROCKHEAD", "Rock Head", "This Pokémon does not suffer recoil damage"),
("DROUGHT", "Drought", "Summons harsh sunlight for five turns"),
("ARENATRAP", "Arena Trap", "Opponents cannot flee or switch out normally"),
("VITALSPIRIT", "Vital Spirit", "This Pokémon cannot fall asleep"),
("WHITESMOKE", "White Smoke", "Others cannot lower this Pokémon's stats"),
("PUREPOWER", "Pure Power", "This Pokémon's Attack stat is doubled in battle"),
("SHELLARMOR", "Shell Armor", "This Pokémon cannot be critically hit"),
("AIRLOCK", "Air Lock", "This Pokémon negates all weather effects in battle"),
("TANGLEDFEET", "Tangled Feet", "This Pokémon is harder to hit when it is confused"),
("MOTORDRIVE", "Motor Drive", "Being hit by an Electric move raises its Speed"),
("RIVALRY", "Rivalry", "Deals more damage to a target of the same gender"),
("STEADFAST", "Steadfast", "Flinching will raise this Pokémon's Speed stat"),
("SNOWCLOAK", "Snow Cloak", "This Pokémon is harder to hit during a hailstorm"),
("GLUTTONY", "Gluttony", "This Pokémon eats its held Berry at half HP already"),
("ANGERPOINT", "Anger Point", "Being critically hit maximizes its Attack stat"),
("UNBURDEN", "Unburden", "Using or losing its held item doubles its Speed"),
("HEATPROOF", "Heatproof", "Only takes halved damage from Fire moves and burns"),
("SIMPLE", "Simple", "Its stats are raised or lowered twice as much"),
("DRYSKIN", "Dry Skin", "Healed by Water moves and rain, damaged more by Fire"),
("DOWNLOAD", "Download", "Raises Attack or Sp. Atk according to its foes"),
("IRONFIST", "Iron Fist", "Punching moves used by it deal more damage"),
("POISONHEAL", "Poison Heal", "Restores HP instead of losing them when poisoned"),
("ADAPTABILITY", "Adaptability", "Damage bonus for same-type moves is doubled"),
("SKILLLINK", "Skill Link", "Its Multi-strike moves hit the max number of times"),
("HYDRATION", "Hydration", "Cures its status conditions during rain"),
("SOLARPOWER", "Solar Power", "Harsh sunlight boosts Sp. Atk, but damages it"),
("QUICKFEET", "Quick Feet", "Status conditions greatly increase its Speed stat"),
("NORMALIZE", "Normalize", "Moves it uses turn Normal-type and deal more damage"),
("SNIPER", "Sniper", "The critical hits it lands deal more damage"),
("MAGICGUARD", "Magic Guard", "This Pokémon can only take direct damage"),
("NOGUARD", "No Guard", "Moves used by or against this Pokémon always hit"),
("STALL", "Stall", "Uses its move after all others of same priority"),
("TECHNICIAN", "Technician", "Greatly boosts its moves with power 60 or less"),
("LEAFGUARD", "Leaf Guard", "Resists status conditions during harsh sunlight"),
("KLUTZ", "Klutz", "It is unable to gain any effect of its held item"),
("MOLDBREAKER", "Mold Breaker", "This Pokémon's moves ignore any Abilities"),
("SUPERLUCK", "Super Luck", "Raises this Pokémon's critical hit chance"),
("AFTERMATH", "Aftermath", "Damages an attacker who makes it faint on contact"),
("ANTICIPATION", "Anticipation", "Senses a supereffective or one-hit KO move"),
("FOREWARN", "Forewarn", "Senses the strongest damaging move of its foes"),
("UNAWARE", "Unaware", "This Pokémon ignores an opponent's stat raises"),
("TINTEDLENS", "Tinted Lens", "Deals double damage with 'not effective' moves"),
("FILTER", "Filter", "Takes less damage from supereffective attacks"),
("SLOWSTART", "Slow Start", "Its Attack and Speed are halved for five turns"),
("SCRAPPY", "Scrappy", "Can hit Ghost-types with Normal and Fighting moves"),
("STORMDRAIN", "Storm Drain", "Attracts Water moves. They raise its Sp. Atk"),
("ICEBODY", "Ice Body", "Slowly regenerates HP during a hailstorm"),
("SOLIDROCK", "Solid Rock", "Takes less damage from supereffective attacks"),
("SNOWWARNING", "Snow Warning", "Summons a hailstorm upon entering battle"),
("HONEYGATHER", "Honey Gather", "May find Honey after a battle"),
("FRISK", "Frisk", "Identifies an opponent's held item when switched in"),
("RECKLESS", "Reckless", "Deals more damage with moves that cause recoil"),
("MULTITYPE", "Multitype", "Matches the type of its held Plate or Z-Crystal"),
("FLOWERGIFT", "Flower Gift", "Harsh sunlight ups its and allies' Attack and Sp. Def"),
("BADDREAMS", "Bad Dreams", "Makes sleeping opponents steadily lose HP"),
("PICKPOCKET", "Pickpocket", "Steals the held item of an attacker on contact"),
("SHEERFORCE", "Sheer Force", "Removes added effects, boosting according moves"),
("CONTRARY", "Contrary", "Inverts this Pokémon's stat raises and lowerings"),
("UNNERVE", "Unnerve", "Prevents opponents from eating their held Berries"),
("DEFIANT", "Defiant", "Sharply raises its Attack if a foe lowers its stats"),
("DEFEATIST", "Defeatist", "Halved Attack and Sp. Atk stats at half HP or lower"),
("CURSEDBODY", "Cursed Body", "May disable a move it is damaged by for four turns"),
("HEALER", "Healer", "Has a good chance to heal an ally's status condition"),
("FRIENDGUARD", "Friend Guard", "Reduces damage to allies while in battle"),
("WEAKARMOR", "Weak Armor", "Physical hits sharply raise Speed, but lower Defense"),
("HEAVYMETAL", "Heavy Metal", "This Pokémon's weight is doubled in battle"),
("LIGHTMETAL", "Light Metal", "This Pokémon's weight is halved in battle"),
("MULTISCALE", "Multiscale", "Only takes halved direct damage if at full HP"),
("TOXICBOOST", "Toxic Boost", "Being poisoned greatly boosts its physical moves"),
("FLAREBOOST", "Flare Boost", "Being burnt greatly boosts its special moves"),
("HARVEST", "Harvest", "May restore its Berry. Ensured in harsh sunlight"),
("TELEPATHY", "Telepathy", "This Pokémon dodges damaging moves of allies"),
("MOODY", "Moody", "Sharply raises a stat and lowers another each turn"),
("OVERCOAT", "Overcoat", "Hail, sandstorm, powder, spores don't affect it"),
("POISONTOUCH", "Poison Touch", "May cause poisoning on contact when attacking"),
("REGENERATOR", "Regenerator", "Regenerates a third of its max HP when switched out"),
("BIGPECKS", "Big Pecks", "Others can't lower this Pokémon's Defense stat"),
("SANDRUSH", "Sand Rush", "A sandstorm doubles this Pokémon's Speed stat"),
("WONDERSKIN", "Wonder Skin", "Lowers the Accuracy of status moves used on it"),
("ANALYTIC", "Analytic", "Deals more damage when moving after its target"),
("ILLUSION", "Illusion", "Appears as the last party member until damaged"),
("IMPOSTER", "Imposter", "Copies its foe's species, moves, Ability and stats"),
("INFILTRATOR", "Infiltrator", "Ignores effects of moves like Reflect or Substitute"),
("MUMMY", "Mummy", "An attacker's Ability will become Mummy on contact"),
("MOXIE", "Moxie", "Knocking out any Pokémon raises its Attack stat"),
("JUSTIFIED", "Justified", "Being damaged by a Dark move raises its Attack"),
("RATTLED", "Rattled", "Bug, Dark, or Ghost move damage raises its Speed"),
("MAGICBOUNCE", "Magic Bounce", "Reflects almost all status moves back to their user"),
("SAPSIPPER", "Sap Sipper", "Being hit by a Grass move raises its Attack stat"),
("PRANKSTER", "Prankster", "Gains increased priority on its status moves"),
("SANDFORCE", "Sand Force", "Sandstorms boost Rock, Ground and Steel moves"),
("IRONBARBS", "Iron Barbs", "Damages any attacker who makes direct contact"),
("ZENMODE", "Zen Mode", "Changes into its Zen Mode if at half HP or below"),
("VICTORYSTAR", "Victory Star", "Increases its and allies' Accuracy slightly"),
("TURBOBLAZE", "Turboblaze", "This Pokémon's moves ignore any Abilities"),
("TERAVOLT", "Teravolt", "This Pokémon's moves ignore any Abilities"),
("AERILATE", "Aerilate", "Boosts its Normal moves, making them Flying-type"),
("AROMAVEIL", "Aroma Veil", "Protects it and allies from move-choice-limiting moves"),
("AURABREAK", "Aura Break", "Inverts the effects of Fairy Aura and Dark Aura"),
("BULLETPROOF", "Bulletproof", "This Pokémon is immune to ball and bomb moves"),
("CHEEKPOUCH", "Cheek Pouch", "Eating a held Berry restores additional HP"),
("COMPETITIVE", "Competitive", "Sharply raises its Sp. Atk if a foe lowers its stats"),
("DARKAURA", "Dark Aura", "Powers up Dark-type moves from any combatant"),
("FAIRYAURA", "Fairy Aura", "Powers up Fairy-type moves from any combatant"),
("FLOWERVEIL", "Flower Veil", "Protects allied Grass-types' status and stats"),
("FURCOAT", "Fur Coat", "This Pokémon's Defense stat is doubled in battle"),
("GALEWINGS", "Gale Wings", "It gains priority on its Flying moves if at full HP"),
("GOOEY", "Gooey", "Lowers the Speed stat of any attacker on contact"),
("GRASSPELT", "Grass Pelt", "Grassy Terrain increases this Pokémon's Defense"),
("MAGICIAN", "Magician", "Damaging a target directly also steals its held item"),
("MEGALAUNCHER", "Mega Launcher", "Boosts its pulse-based moves and Aura Sphere"),
("PARENTALBOND", "Parental Bond", "Strikes single targets a second time with low power"),
("PIXILATE", "Pixilate", "Boosts its Normal moves, making them Fairy-type"),
("PROTEAN", "Protean", "Matches the type of the move it is about to use"),
("REFRIGERATE", "Refrigerate", "Boosts its Normal moves, making them Ice-type"),
("STANCECHANGE", "Stance Change", "Depending on the move it uses, it switches Formes"),
("STRONGJAW", "Strong Jaw", "Biting moves used by it are powered up greatly"),
("SWEETVEIL", "Sweet Veil", "This Pokémon and its allies cannot fall asleep"),
("SYMBIOSIS", "Symbiosis", "Will pass its held item to an ally who used their own"),
("TOUGHCLAWS", "Tough Claws", "Deals more damage with moves that make contact"),
("PRIMORDIALSEA", "Primordial Sea", "Summons insurmountable heavy rain"),
("DESOLATELAND", "Desolate Land", "Summons overbearing, extremely harsh sunlight"),
("DELTASTREAM", "Delta Stream", "Summons a powerful mysterious air current"),
("BATTERY", "Battery", "Considerably boosts its allies' special moves"),
("BEASTBOOST", "Beast Boost", "Knocking out any Pokémon raises its highest stat"),
("BERSERK", "Berserk", "Raises its Sp. Atk when a hit drops its HP below half"),
("COMATOSE", "Comatose", "It is always asleep, but can still attack normally"),
("CORROSION", "Corrosion", "This Pokémon can poison Steel- and Poison-types"),
("DANCER", "Dancer", "It instantly copies dance moves used by combatants"),
("DAZZLING", "Dazzling", "Prevents foes' single-target priority moves"),
("ELECTRICSURGE", "Electric Surge", "Turns the battlefield into Electric Terrain"),
("EMERGENCYEXIT", "Emergency Exit", "When dropping to half HP or less, it switches out"),
("FLUFFY", "Fluffy", "Halves contact and doubles Fire damage taken"),
("FULLMETALBODY", "Full Metal Body", "Others cannot lower this Pokémon's stats"),
("GALVANIZE", "Galvanize", "Boosts its Normal moves, making them Electric-type"),
("GRASSYSURGE", "Grassy Surge", "Turns the battlefield into Grassy Terrain"),
("INNARDSOUT", "Innards Out", "Deals equal damage to an attacker knocking it out"),
("LIQUIDVOICE", "Liquid Voice", "Changes its sound-based moves to Water-type"),
("LONGREACH", "Long Reach", "Never makes direct contact when attacking"),
("MERCILESS", "Merciless", "Poisoned targets will always be critically hit"),
("MISTYSURGE", "Misty Surge", "Turns the battlefield into Misty Terrain"),
("POWEROFALCHEMY", "Alchemy Power", "Takes over the Ability of a fainting ally"),
("PRISMARMOR", "Prism Armor", "Takes less damage from supereffective attacks"),
("PSYCHICSURGE", "Psychic Surge", "Turns the battlefield into Psychic Terrain"),
("QUEENLYMAJESTY", "Queen Majesty", "Prevents foes' single-target priority moves"),
("RECEIVER", "Receiver", "Takes over the Ability of a fainting ally"),
("SHADOWSHIELD", "Shadow Shield", "Only takes halved direct damage if at full HP"),
("SLUSHRUSH", "Slush Rush", "This Pokémon's Speed stat is doubled during hail"),
("SOULHEART", "Soul-Heart", "Whenever a combatant faints, its Sp. Atk raises"),
("STAKEOUT", "Stakeout", "Deals double damage if the target is switched out"),
("STAMINA", "Stamina", "When hit by an attack, its Defense stat is raised"),
("STEELWORKER", "Steelworker", "Deals greatly more damage with Steel-type moves"),
("SURGESURFER", "Surge Surfer", "Electric Terrain doubles this Pokémon's Speed stat"),
("TANGLINGHAIR", "Tangling Hair", "Lowers the Speed stat of any attacker on contact"),
("TRIAGE", "Triage", "Gains high priority for its HP-restoring moves"),
("WATERBUBBLE", "Water Bubble", "Double damage with Water moves. Can't be burnt"),
("WATERCOMPACTION", "Water Compact", "Being hit by a Water move raises its Defense stat"),
("WIMPOUT", "Wimp Out", "When dropping to half HP or less, it switches out"),
("SCHOOLING", "Schooling", "Takes on a School Form as long as above 25% HP"),
("RKSSYSTEM", "RKS System", "This Pokémon matches the type of its held Memory"),
("SHIELDSDOWN", "Shields Down", "Loses its protective Meteor Form below half HP"),
("DISGUISE", "Disguise", "Once a battle, it is not damaged by the first hit"),
("POWERCONSTRUCT", "Power Constr.", "When HP are half or less, enters Complete Forme"),
("NEUROFORCE", "Neuroforce", "Deals more damage with supereffective moves");